# Generated by Django 5.2.17 on 2026-09-01 02:45

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shipments', '0003_tracking_operations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12, unique=True, verbose_name='código anónimo')),
                ('area', models.CharField(choices=[('ADMINISTRATIVE', 'Administrativa'), ('OPERATIONAL', 'Operativa')], max_length=20, verbose_name='área')),
                ('notes', models.CharField(blank=True, max_length=250, verbose_name='observaciones')),
                ('is_active', models.BooleanField(default=True, verbose_name='participante activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='research_participants_created', to=settings.AUTH_USER_MODEL, verbose_name='registrado por')),
            ],
            options={
                'verbose_name': 'participante anónimo',
                'verbose_name_plural': 'participantes anónimos',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CustomerNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('STATUS', 'Cambio de estado'), ('INCIDENT', 'Incidencia reportada'), ('RESOLVED', 'Incidencia resuelta'), ('DELIVERY', 'Entrega confirmada')], max_length=10, verbose_name='evento')),
                ('recipient_email', models.EmailField(blank=True, max_length=254, verbose_name='correo de destino')),
                ('subject', models.CharField(max_length=180, verbose_name='asunto')),
                ('message', models.TextField(max_length=1200, verbose_name='mensaje')),
                ('status', models.CharField(choices=[('SENT', 'Enviada'), ('SKIPPED', 'Omitida'), ('FAILED', 'Fallida')], max_length=8, verbose_name='resultado')),
                ('error_message', models.CharField(blank=True, max_length=300, verbose_name='detalle del resultado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha y hora')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_notifications', to='shipments.shipment', verbose_name='envío')),
            ],
            options={
                'verbose_name': 'notificación automática',
                'verbose_name_plural': 'notificaciones automáticas',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='research_notice_status_idx')],
            },
        ),
        migrations.CreateModel(
            name='OperationMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('QUERY', 'Consulta de seguimiento'), ('UPDATE', 'Actualización de estado')], max_length=8, verbose_name='operación')),
                ('source', models.CharField(choices=[('PUBLIC', 'Consulta pública'), ('INTERNAL', 'Consulta interna'), ('STATUS', 'Flujo de estados')], max_length=10, verbose_name='origen')),
                ('success', models.BooleanField(verbose_name='operación exitosa')),
                ('duration_ms', models.PositiveIntegerField(verbose_name='duración en milisegundos')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='detalle técnico')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha y hora')),
                ('shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_metrics', to='shipments.shipment', verbose_name='envío')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_metrics', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'métrica automática',
                'verbose_name_plural': 'métricas automáticas',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['operation', 'created_at'], name='research_metric_op_idx'), models.Index(fields=['success', 'created_at'], name='research_metric_ok_idx')],
            },
        ),
        migrations.CreateModel(
            name='ResponseTimeObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('PRETEST', 'Pretest'), ('POSTTEST', 'Postest')], max_length=8, verbose_name='medición')),
                ('operation', models.CharField(choices=[('QUERY', 'Consulta del estado de un envío'), ('UPDATE', 'Actualización del estado de un paquete')], max_length=8, verbose_name='operación observada')),
                ('started_at', models.DateTimeField(verbose_name='fecha y hora de inicio')),
                ('finished_at', models.DateTimeField(verbose_name='fecha y hora de finalización')),
                ('duration_seconds', models.DecimalField(decimal_places=3, editable=False, max_digits=12, verbose_name='duración en segundos')),
                ('notes', models.CharField(blank=True, max_length=300, verbose_name='observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='response_time_observations', to=settings.AUTH_USER_MODEL, verbose_name='registrado por')),
            ],
            options={
                'verbose_name': 'observación de tiempo de respuesta',
                'verbose_name_plural': 'observaciones de tiempos de respuesta',
                'ordering': ['-started_at', '-id'],
                'indexes': [models.Index(fields=['phase', 'operation'], name='research_time_phase_idx')],
            },
        ),
        migrations.CreateModel(
            name='EfficiencySurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('PRETEST', 'Pretest'), ('POSTTEST', 'Postest')], max_length=8, verbose_name='medición')),
                ('observed_on', models.DateField(default=django.utils.timezone.localdate, verbose_name='fecha de aplicación')),
                ('q1', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='P1 · Rapidez de atención')),
                ('q2', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='P2 · Exactitud de ubicación')),
                ('q3', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='P3 · Resolución de problemas')),
                ('q4', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='P4 · Tiempo de registro')),
                ('q5', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='P5 · Atención en ventanilla')),
                ('q6', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='P6 · Organización del personal')),
                ('q7', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='P7 · Condición de encomiendas')),
                ('q8', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='P8 · Organización del almacén')),
                ('q9', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='P9 · Exactitud sistema/almacén')),
                ('q10', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='P10 · Eficiencia general')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='efficiency_surveys_recorded', to=settings.AUTH_USER_MODEL, verbose_name='registrado por')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='surveys', to='research.studyparticipant', verbose_name='participante')),
            ],
            options={
                'verbose_name': 'cuestionario de eficiencia',
                'verbose_name_plural': 'cuestionarios de eficiencia',
                'ordering': ['phase', 'participant__code'],
                'indexes': [models.Index(fields=['phase', 'observed_on'], name='research_survey_phase_idx')],
                'constraints': [models.UniqueConstraint(fields=('participant', 'phase'), name='research_unique_survey_phase')],
            },
        ),
        migrations.CreateModel(
            name='TraceabilityObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('PRETEST', 'Pretest'), ('POSTTEST', 'Postest')], max_length=8, verbose_name='medición')),
                ('observed_on', models.DateField(default=django.utils.timezone.localdate, verbose_name='fecha de observación')),
                ('total_registered', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='total de envíos registrados')),
                ('correctly_tracked', models.PositiveIntegerField(verbose_name='envíos rastreados correctamente')),
                ('notes', models.CharField(blank=True, max_length=300, verbose_name='observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traceability_observations', to=settings.AUTH_USER_MODEL, verbose_name='registrado por')),
            ],
            options={
                'verbose_name': 'observación de trazabilidad',
                'verbose_name_plural': 'observaciones de trazabilidad',
                'ordering': ['-observed_on', '-id'],
                'indexes': [models.Index(fields=['phase', 'observed_on'], name='research_trace_phase_idx')],
            },
        ),
    ]
